name: Code Quality

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov radon
    
    - name: Run tests with coverage
      run: |
        if [ -d "tests" ] || ls test_*.py 2>/dev/null | grep -q .; then
          pytest --cov=app --cov-report=xml --cov-report=term
        else
          echo "ℹ️ No tests found, skipping coverage"
        fi
      continue-on-error: true
    
    - name: Upload coverage to Codecov
      if: success()
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
    
    - name: Calculate code metrics
      run: |
        echo "## Code Metrics" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Cyclomatic Complexity" >> $GITHUB_STEP_SUMMARY
        radon cc app/ -a -s >> $GITHUB_STEP_SUMMARY || true
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Maintainability Index" >> $GITHUB_STEP_SUMMARY
        radon mi app/ -s >> $GITHUB_STEP_SUMMARY || true
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Raw Metrics" >> $GITHUB_STEP_SUMMARY
        radon raw app/ -s >> $GITHUB_STEP_SUMMARY || true
