name: Dependency Check

on:
  schedule:
    # Run weekly on Monday at 9:00 UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  check-dependencies:
    name: Check for outdated dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-audit safety
        pip install -r requirements.txt
    
    - name: Check for security vulnerabilities
      run: |
        echo "## Security Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        safety check --json > safety-report.json || true
        if [ -s safety-report.json ]; then
          echo "⚠️ Security vulnerabilities found. Check the report below." >> $GITHUB_STEP_SUMMARY
          cat safety-report.json >> $GITHUB_STEP_SUMMARY
        else
          echo "✅ No known security vulnerabilities found." >> $GITHUB_STEP_SUMMARY
        fi
    
    - name: Audit dependencies with pip-audit
      run: |
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Pip Audit Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        pip-audit --desc || echo "⚠️ Some vulnerabilities found" >> $GITHUB_STEP_SUMMARY
    
    - name: Check for outdated packages
      run: |
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Outdated Packages" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        pip list --outdated >> $GITHUB_STEP_SUMMARY || echo "All packages are up to date" >> $GITHUB_STEP_SUMMARY
